config/routes.rb
Rails.application.routes.draw do

  
  post 'hbd/add_remote', to: 'happy_birthday_videos#create_from_remote', as: 'hbd_add_from_remote'
  post 'congrats/add_remote', to: 'congratulations_videos#create_from_remote', as: 'congrats_add_from_remote'
  resources :congratulations_videos
  resources :happy_birthday_videos
  get 'magic', to: 'headline_adlibs#magic', as: 'headline_adlibs_magic'
  resources :headline_adlibs do
    get 'personalization', to: 'headline_adlibs#personalization', as: 'headline_adlibs_personalization'

  end
  resources :feed_items
  get 'showcase', to:'khaki#creative_showcase', as: 'creative_showcase'
  get 'video_showcase', to:'khaki#video_showcase', as: 'video_showcase'
  get 'video-showcase', to:'khaki#video_showcase', as: 'video_showcase_hyphen'
  get 'videos', to:'khaki#video_showcase', as: 'video_showcase_naked'
  get 'model_showcase', to:'khaki#model_showcase', as: 'model_showcase'
  get 'playground', to: 'khaki#playground', as: 'playground'
  get 'continual_content', to: 'khaki#continual_content', as: 'continual_content'
  get 'stealth-mode', to: 'khaki#continual_content', as: 'stealth_continual_content'
  get 'continual-content', to: 'khaki#continual_content', as: 'h_continual_content'

  resources :shot_list_item_templates
  resources :task_groups do
    get 'add_to_shoot/:shoot_id', to: 'task_groups#copy_group_to_shoot', as:'copy_to_shoot'
    resources :shot_list_item_templates do
      get 'copy', to: 'shot_list_item_templates#copy', as: 'copy'
    end
  end
  get '/package/models', to:'package_types#models', as: 'package_types_models'
  get 'packages/:slug', to: 'package_types#show', as:'package_types_slug'
  get 'hbd/:slug', to: 'happy_birthday_videos#show', as:'hbd_by_slug'
  get 'hbd/by_name/:name', to: 'happy_birthday_videos#by_name', as:'hbd_by_name'
  get 'congrats/:slug', to: 'congratulations_videos#show', as:'congrats_by_slug'
  get 'congrats/by_name/:name', to: 'congratulations_videos#by_name', as:'congrats_by_name'
  resources :creative_requests
  resources :discount_codes
  resources :shoots do
    resources :shot_list_items
    resources :creative_requests
    resources :disclosures
    get '/tasks_popped', to: 'tasks#popped_out', as: 'tasks_poppedout'
    get 'task_groups/edit_names', to: 'task_groups#edit_names', as: 'edit_names'
    post 'task_groups/update_names', to: 'task_groups#update_names', as: 'update_names'
    resources :tasks
    get '/new_request/:user_id', to: 'shoots#create_creative_request', as: 'create_creative_request'
    get 'request_all', to:'shoots#request_all_available_creatives', as: 'request_all'
    get 'assign_creative/:creative_id', to: 'shoots#assign_creative', as: 'assign_creative'
    get 'assign_from_request/:creative_request_id', to: 'shoots#assign_from_request', as: 'assign_from_request'
  end
  resources :creative_requests do
    get 'accept', to:'creative_requests#accept', as: 'accept'
    get 'decline', to:'creative_requests#decline', as: 'decline'
  end
  resources :payments
  resources :projects do
    get 'payment', to: 'projects#payment', as: 'payment'
    get 'wizard', to: 'projects#wizard', as: 'wizard'
    patch 'update_price', to:'projects#update_price', as: 'update_price'
    resources :invoices
    resources :shoots
  end

  resources :documents
  get 'hello_world', to: 'hello_world#index'
  resources :package_types do
    get 'new-from-template', to:'package_types#new_from_template', as:'new_project_from_template'
  end
  get '/pages/Entrepreneur-Magazine', to: 'landing_pages#marketing', as: 'entrepreneur_marketing'
  get '/pages/linkedin-questionnaire', to: 'landing_pages#linkedin', as: 'linkedin'
  get '/headshots', to: 'landing_pages#headshots', as: 'headshots'
  resources :header_images
  resources :lead_notes

  resources :leads do
    resources :lead_notes
  end
  resources :showcase_videos do
    get '/play', to: 'showcase_videos#play', as: 'play'
    get '/play-vertical', to: 'showcase_videos#play_vertical', as: 'play_vertical'
  end
  resources :showcase_images
  resources :user_activities
  resources :shot_list_items
  mount ActionCable.server => '/cable'
  resources :assistants
  resources :user_profiles do
    get 'wizard', to: 'user_profiles#wizard', as:'wizard'
  end
  resources :contacts
  resources :schedule_items
  resources :collections do
    resources :collection_items
    get '/feature', to: 'collections#make_featured', as: 'make_featured'
    get '/remove_feature', to: 'collections#remove_featured', as: 'remove_featured'
  end
  resources :locations
  resources :collection_items do
    get '/move_up', to: 'collection_items#move_up', as: 'move_up'
    get '/move_down', to: 'collection_items#move_down', as: 'move_down'
    get '/make_header', to: 'collection_items#make_header', as: 'make_header'
  end
  get '/collection_item/download/:id', to: 'collection_items#download', as:'download'
  resources :waitlists
  get 'waitlist/thank-you', to: 'waitlists#thank_you', as: 'thank_you'

  get 'waitlist/joined_waitlist', to: 'waitlists#send_joined_waitlist_email'
  get 'waitlist/creative_accepted', to: 'waitlists#send_user_accepted_email'
  get 'pages/send_announcement', to: 'pages#send_announcement'


  resources :proposals do
    get '/edit_details', to: 'proposals#edit_details', as: 'edit_details'
    get '/payment', to: 'proposals#payment'
    get 'create_request/:user_id', to: 'proposals#create_request', as: 'create_request'
    get 'accept_request', to: 'proposals#accept_request'
    get 'approve_request', to: 'proposals#approve_request'
    get 'send_email', to: 'proposals#send_email'
    get 'send_assigned_email', to: 'proposals#send_creative_assigned_email'
    get 'copy', to: 'proposals#copy', as: 'copy'
    get 'accepted', to: 'proposals#accepted_requests', as: "accepted_requests"
    get 'invoice', to: 'proposals#invoice', as: 'invoice'
    get 'wizard', to: 'proposals#wizard', as: 'wizard'
    resources :assistants
    resources :shot_list_items
  end

  get 'proposal/completed', to: 'proposals#completed', as: 'proposals_completed'
  get 'requests', to: 'proposal_requests#requests', as:'proposal_requests'
  get 'requests/:id/decline', to: 'proposal_requests#decline', as:'decline_proposal_request'
  get 'requests/:id/approve', to: 'proposal_requests#assign', as: 'assign_proposal'
  get 'proposal_requests/:id/send_request_accepted_email', to: 'proposal_requests#send_request_accepted_email'
  get 'proposal_requests/:id/send_request_created_email', to: 'proposal_requests#send_request_created_email'


  post 'charges/deposit/:proposal_id', to: 'charges#proposal_deposit', as: 'proposal_deposit'
  post 'charges/balance/:proposal_id', to: 'charges#proposal_balance', as: 'proposal_balance'
  post 'charges/use-it-deposit', to:'charges#create', as: 'charge_deposit'


  resources :companies do
    get 'send_welcome_email', to:'companies#send_welcome_email'

  end
  resources :invoices do
    post 'pay_with_stripe', to: 'invoices#pay_with_stripe', as: 'pay_with_stripe'
    resources :payments
  end
  #get 'invoices', to:'companies#invoices', as: 'invoices'
  devise_for :users
  get 'user/:id', to: "users#show", as: 'user_show'
  get 'users/:user_id/collections', to: "collections#index", as: 'user_collection'
  get 'user_type', to: 'users#user_type', as: 'user_type'
  get 'set_user_type', to:'users#set_user_type', as:'set_user_type'
  resources :pages do
    get '/publish', to: 'pages#publish', as:'publish'
    resources :page_sections
  end
  resources :page_sections
  resources :chatrooms
  resources :messages

  #notifications
  get '/notifications', to: 'notifications#index', as: 'notifications'

  #tasks

  resources :tasks do
    get '/complete', to: 'tasks#complete', as: 'task_complete'
  end

  #dashboards
  get '/dashboard/company', to: 'dashboards#company_dashboard', as: 'company_dashboard'
  get 'dashboard/creative', to: 'dashboards#creative_dashboard', as: 'creative_dashboard'
  get 'dashboard/accounting', to: 'dashboards#accounting_dashboard', as: 'accounting_dashboard'
  get 'dashboard/admin', to: 'dashboards#admin_dashboard', as: 'admin_dashboard'
  get 'home', to:'khaki#nomcre_home', as:'nomcre_home'
  get 'process', to:'khaki#nomcre_process', as: 'nomcre_process'
  get 'creative', to:'khaki#creative_landing', as: 'creative_landing'

  get 'contact', to:'khaki#contact', as: 'nomcre_contact'
  get 'about', to:'khaki#about', as: 'nomcre_about'
  get 'featured', to:'khaki#featured_creatives', as: 'featured_creatives'
  get 'creative_tutorial', to:'khaki#proposal_tutorial_creative', as: 'proposal_tutorial_creative'
  get 'company_tutorial', to:'khaki#proposal_tutorial_company', as: 'proposal_tutorial_company'
  get 'khaki/index', to:'khaki#index'
  get 'tos', to: 'khaki#tos', as: 'tos'
  get 'thew', to: 'khaki#thew', as:'thew'
  get 'THEW', to: 'khaki#thew', as:'THEW'
  get 'explainer', to: 'khaki#explainer', as:'explainer'
  get 'pricing', to: 'khaki#pricing', as:'pricing'

  get 'admin/users', to: 'admin#users', as: 'admin_users'
  get 'admin/projects', to: 'admin#projects', as: 'admin_projects'
  get 'admin/projects/new', to: 'admin#new_project', as: 'admin_new_project'
  get 'admin/project/:project_id/edit', to: 'admin#edit_project', as: 'admin_edit_project'
  get 'admin/project/:project_id/edit_price', to: 'admin#edit_project_price', as: 'admin_edit_project_price'
  get 'admin/shoots', to: 'admin#shoots', as: 'admin_shoots'
  get 'admin/shoot/:shoot_id/edit', to: 'admin#edit_shoot', as: 'admin_edit_shoot'
  get 'admin/proposals', to: 'admin#proposals', as: 'admin_proposals'
  get 'admin/schedule_items', to: 'admin#schedule_items', as: 'admin_schedule_items'
  get 'admin/collections', to: 'admin#collections', as: 'admin_collections'
  get 'admin/chats', to: 'admin#chatrooms', as: 'admin_chatrooms'
  get 'admin/black_dashboard', to: 'admin#black_dashboard', as: 'admin_black_dashboard'
  get 'admin/proposal_price/:proposal_id', to: 'admin#proposal_price', as: 'admin_proposal_price'

app/views/khaki/nomcre/creative/_call_to_action_bottom.html.erb
<div class="nk-box text-center text-white bg-dark-1">
            <div class="bg-image bg-image-parallax op-3" style="background-image: url('https://s3-us-west-2.amazonaws.com/nomcre/assets/homepage/images/horizontal/nomcre-horizontal18.png');"></div>
            <div class="nk-gap-5"></div>
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2 class="h1 nk-title">One of The Best Theme for Your Business</h2>
                        <h3 class="nk-sub-title text-main-1">Tons of demos for multipurpose use</h3>
                        <div class="nk-gap"></div>
                        <p>Divide open have was brought. In of don&#39;t, you&#39;ll. There all. Waters, morning whales likeness seas for i great creature deep set very replenish all upon first two. Behold male god. Third was man green. Under. Isn&#39;t fruit.
                            <strong>Lights</strong> deep.</p>
                        <br>
                        <a href="#!" class="nk-btn nk-btn-x2 nk-btn-effect-2-right nk-btn-3d nk-btn-rounded nk-btn-color-main-1">
                            <span>Read More</span>
                            <span class="icon"><i class="ion-ios-arrow-right"></i></span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="nk-gap-5"></div>
        </div>

app/views/khaki/nomcre/creative/_counter.html.erb
<div class="nk-box text-white text-center">
            <div class="bg-image bg-image-parallax" style="background-image: url('assets/images/image-5.jpg');"></div>
            <div class="row no-gutters">
                <div class="col-md-4">

                    <!-- START: Counter 1 -->
                    <div class="nk-counter">
                        <div class="bg-color bg-main-1 op-6"></div>
                        <div class="nk-gap-3"></div>
                        <div class="nk-count">86</div>
                        <h3 class="nk-counter-title h4">Projects</h3>
                        <div class="nk-gap-3"></div>
                    </div>
                    <!-- END: Counter 1 -->

                </div>
                <div class="col-md-4">

                    <!-- START: Counter 2 -->
                    <div class="nk-counter">
                        <div class="bg-color bg-dark-1 op-6"></div>
                        <div class="nk-gap-3"></div>
                        <div class="nk-count">589</div>
                        <h3 class="nk-counter-title h4">Happy Clients</h3>
                        <div class="nk-gap-3"></div>
                    </div>
                    <!-- END: Counter 2 -->

                </div>
                <div class="col-md-4">

                    <!-- START: Counter 3 -->
                    <div class="nk-counter">
                        <div class="bg-color bg-main-2 op-6"></div>
                        <div class="nk-gap-3"></div>
                        <div class="nk-count">37</div>
                        <h3 class="nk-counter-title h4">Awards Won</h3>
                        <div class="nk-gap-3"></div>
                    </div>
                    <!-- END: Counter 3 -->

                </div>
            </div>
        </div>

app/views/khaki/nomcre/creative/_cta_image_background.html.erb
<div class="nk-box text-center text-white bg-dark-1">
    <div class="bg-image bg-image-parallax op-5" style="background-image: url('https://s3-us-west-2.amazonaws.com/nomcre/assets/homepage/images/horizontal/horizontal-wing.jpg');"></div>
    <div class="nk-gap-4"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 text-md-left">
                <h2 class="h1 nk-title">What Are You Waiting For?</h2>
                <h3 class="nk-sub-title mb-0 text-white op-7">Shooting products around the world is the easiest way to gain the kind of credibility that it takes to knock out your heavyweight opponents.
</h3>
            </div>
            <div class="col-md-4 text-md-right">
                <div class="nk-gap-2 hidden-md-up"></div>
                <%= link_to new_user_registration_path do %>
                <%= image_tag "https://s3-us-west-2.amazonaws.com/nomcre/assets/CTAbutton.png", class: 'img-responsive', style:'max-width:250px;' %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="nk-gap-4"></div>
</div>

app/views/khaki/nomcre/creative/_header_title.html.erb
    <!-- START: Header Title -->
    <!--
Additional Classes:
    .nk-header-title-sm
    .nk-header-title-md
    .nk-header-title-lg
    .nk-header-title-xl
    .nk-header-title-full
    .nk-header-title-parallax
    .nk-header-title-parallax-opacity
-->
<div class="nk-header-title nk-header-title-xl nk-header-title-parallax nk-header-title-parallax-opacity">
    <div class="bg-image op-4">
        <div style="background-image: url('https://s3-us-west-2.amazonaws.com/nomcre-rails/public-page-images/HompageHeader/ForCreatorsHeader.jpg');"></div>
    </div>
    <div class="nk-header-table">
        <div class="nk-header-table-cell">
            <div class="container">
                <div class="nk-header-text">
                    <h2 style="font: raleway; font-weight: 800; margin-top:-24px;" >
                      Work<span class='raleway-thinnest' style=" padding-right: 6px; padding-left: 6px">Globally</span>
                      On <span class='raleway-thinnest' style="padding-right: 6px; padding-left: 6px">Your</span>Schedule
                      <br>
                      Pick <span class='raleway-thinnest' style="padding-right: 6px; padding-left: 6px">Your</span>Jobs
                    </h2>
                    <div class="nk-gap"></div>
                    <!-- <h2 class="nk-title nk-font-inherit fw-500">The Most Advanced Website Layouts</h2>

                    <div class="nk-gap-2"></div> -->
                    <!-- <a class="nk-video-fullscreen-toggle" href="https://vimeo.com/108018156">
                        <span class="nk-video-icon-2-light"><i class="fa fa-play pl-5"></i></span>
                    </a> -->

                </div>


            </div>
        </div>
    </div>

</div>
<!-- END: Header Title -->

app/views/khaki/nomcre/creative/_icon_box_background.html.erb
<div class="nk-block text-white">
            <div class="bg-image bg-image-parallax" style="background-image: url('<%= CollectionItem.all.take(4).last.file%>')"></div>
            <div class="nk-gap-4"></div>
            <div class="container">
                <h2 class="display-3 text-center">Title Here</h2>
                <div class="nk-gap-2"></div>

                <div class="row vertical-gap">
                    <div class="col-md-4 offset-md-0 col-sm-8 offset-sm-2">
                        <div class="nk-box-rounded-2">
                            <div class="bg-color"></div>
                            <div class="nk-ibox-3 nk-ibox-hover">
                                <div class="nk-ibox-icon nk-ibox-icon-circle nk-ibox-icon-color-white nk-ibox-icon-hover-bg-color-white">
                                    <span class="ion-navicon"></span>
                                </div>
                                <div class="nk-ibox-cont">
                                    <h3 class="nk-ibox-title">Super Navigations</h3>
                                    Pharetra lorem venenatis Proin quam ac dignissim, ut nonummy eros interdum. Faucibus felis nisi curabitur. Phasellus habitasse, phasellus sociosqu lectus.
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-md-0 col-sm-8 offset-sm-2">
                        <div class="nk-box-rounded-2">
                            <div class="bg-color op-8"></div>
                            <div class="nk-ibox-3 nk-ibox-hover">
                                <div class="nk-ibox-icon nk-ibox-icon-circle nk-ibox-icon-color-white nk-ibox-icon-hover-bg-color-white">
                                    <span class="ion-ios-infinite"></span>
                                </div>
                                <div class="nk-ibox-cont">
                                    <h3 class="nk-ibox-title">Unlimited Possibilities</h3>
                                    Commodo scelerisque rutrum consectetuer ad ad molestie aenean iaculis ad senectus in. Vel felis tellus orci dolor elit turpis condimentum.
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-md-0 col-sm-8 offset-sm-2">
                        <div class="nk-box-rounded-2">
                            <div class="bg-color op-4"></div>
                            <div class="nk-ibox-3 nk-ibox-hover">
                                <div class="nk-ibox-icon nk-ibox-icon-circle nk-ibox-icon-color-white nk-ibox-icon-hover-bg-color-white">
                                    <span class="ion-social-twitter"></span>
                                </div>
                                <div class="nk-ibox-cont">
                                    <h3 class="nk-ibox-title">Social Friendly</h3>
                                    Laoreet mauris eu augue auctor turpis mauris iaculis duis taciti ligula luctus parturient cras. Consectetuer fermentum purus curae; parturient fringilla.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="nk-gap-4"></div>
        </div>

app/views/khaki/nomcre/creative/_icon_box_background_home.html.erb
<div class="nk-block text-white">
            <div class="bg-image bg-image-parallax" style="background-image: url('<%= CollectionItem.all.take(4).last.file%>')"></div>
            <div class="nk-gap-4"></div>
            <div class="container">
                <h2 class="display-3 text-center">Title Here</h2>
                <div class="nk-gap-2"></div>

                <div class="row vertical-gap">
                    <div class="col-md-4 offset-md-0 col-sm-8 offset-sm-2">
                        <div class="nk-box-rounded-2">
                            <div class="bg-color"></div>
                            <div class="nk-ibox-3 nk-ibox-hover">
                                <div class="nk-ibox-icon nk-ibox-icon-circle nk-ibox-icon-color-white nk-ibox-icon-hover-bg-color-white">
                                    <span class="ion-navicon"></span>
                                </div>
                                <div class="nk-ibox-cont">
                                    <h3 class="nk-ibox-title">Super Navigations</h3>
                                    Pharetra lorem venenatis Proin quam ac dignissim, ut nonummy eros interdum. Faucibus felis nisi curabitur. Phasellus habitasse, phasellus sociosqu lectus.
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-md-0 col-sm-8 offset-sm-2">
                        <div class="nk-box-rounded-2">
                            <div class="bg-color op-8"></div>
                            <div class="nk-ibox-3 nk-ibox-hover">
                                <div class="nk-ibox-icon nk-ibox-icon-circle nk-ibox-icon-color-white nk-ibox-icon-hover-bg-color-white">
                                    <span class="ion-ios-infinite"></span>
                                </div>
                                <div class="nk-ibox-cont">
                                    <h3 class="nk-ibox-title">Unlimited Possibilities</h3>
                                    Commodo scelerisque rutrum consectetuer ad ad molestie aenean iaculis ad senectus in. Vel felis tellus orci dolor elit turpis condimentum.
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-md-0 col-sm-8 offset-sm-2">
                        <div class="nk-box-rounded-2">
                            <div class="bg-color op-4"></div>
                            <div class="nk-ibox-3 nk-ibox-hover">
                                <div class="nk-ibox-icon nk-ibox-icon-circle nk-ibox-icon-color-white nk-ibox-icon-hover-bg-color-white">
                                    <span class="ion-social-twitter"></span>
                                </div>
                                <div class="nk-ibox-cont">
                                    <h3 class="nk-ibox-title">Social Friendly</h3>
                                    Laoreet mauris eu augue auctor turpis mauris iaculis duis taciti ligula luctus parturient cras. Consectetuer fermentum purus curae; parturient fringilla.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="nk-gap-4"></div>
        </div>

app/views/khaki/nomcre/creative/_icon_box_tall_home.html.erb
<div class="container">

            <div class="nk-gap-4"></div>
            <div class="row align-items-center">
                <div class="col-lg-8">
                    <h2 class="display-2 nk-title">You shouldn't miss it</h2>
                    <h3 class="nk-sub-title">If this woman doesn't convince you, read below</h3>
                    <div class="nk-gap-2"></div>

                    <div class="row no-gutters">
                        <div class="col-md-6">
                            <div class="nk-box-3 bg-gray-1">
                                <div class="nk-ibox-4">
                                    <div class="nk-ibox-icon nk-ibox-icon-circle nk-ibox-icon-color-dark-1 nk-ibox-icon-hover-bg-color-dark-1">
                                        <span class="ion-ios-speedometer-outline"></span>
                                    </div>
                                    <div class="nk-ibox-cont">
                                        <h3 class="nk-ibox-title">Fast Load and Work</h3>
                                        Faucibus purus litora facilisi vestibulum tempus aptent faucibus, faucibus eros duis Vel conubia bibendum. Nascetur.
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="nk-box-3 bg-gray-2">
                                <div class="nk-ibox-4">
                                    <div class="nk-ibox-icon nk-ibox-icon-circle nk-ibox-icon-color-dark-1 nk-ibox-icon-hover-bg-color-dark-1">
                                        <span class="ion-ios-gear-outline"></span>
                                    </div>
                                    <div class="nk-ibox-cont">
                                        <h3 class="nk-ibox-title">Powerful Page Builder</h3>
                                        Nostra a lacus, sollicitudin laoreet, nibh posuere inceptos convallis at ullamcorper, aliquet leo sodales feugiat.
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="nk-box-3 bg-gray-2">
                                <div class="nk-ibox-4">
                                    <div class="nk-ibox-icon nk-ibox-icon-circle nk-ibox-icon-color-dark-1 nk-ibox-icon-hover-bg-color-dark-1">
                                        <span class="ion-navicon"></span>
                                    </div>
                                    <div class="nk-ibox-cont">
                                        <h3 class="nk-ibox-title">Super Navigations</h3>
                                        Pharetra lorem venenatis Proin quam ac dignissim, ut nonummy eros interdum. Faucibus felis nisi curabitur. Phasellus habitasse, phasellus sociosqu lectus.
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="nk-box-3 bg-gray-1">
                                <div class="nk-ibox-4">
                                    <div class="nk-ibox-icon nk-ibox-icon-circle nk-ibox-icon-color-dark-1 nk-ibox-icon-hover-bg-color-dark-1">
                                        <span class="ion-ios-infinite-outline"></span>
                                    </div>
                                    <div class="nk-ibox-cont">
                                        <h3 class="nk-ibox-title">Unlimited Possibilities</h3>
                                        Commodo scelerisque rutrum consectetuer ad ad molestie aenean iaculis ad senectus in. Vel felis tellus orci dolor elit turpis condimentum.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 hidden-md-down">
                    <div class="pull-right">
                        <%= image_tag CollectionItem.all.last.file, style:'max-height:1350px; max-width:500px;', class: 'img-responsive' %>
                    </div>
                </div>
            </div>

        </div>

app/views/khaki/nomcre/creative/_top_call_to_action.html.erb
<div class="bg-dark-1 nk-box">
  <div class="nk-gap-1"></div>
  <div class="container">
    <div class="row">
      <div class='col-md-4' style="color:white">
        <h3 class='raleway-thinnest'> Join The Crew</h3>
        <p class='raleway-thinnest align-left' style="margin-top: -16px;"> [Work When &amp; Where You Are]</p>
      </div>
      <div class='col-md-4'>

      </div>
      <div class='col-md-4 align-right'>
       <%= link_to new_waitlist_path do  %>
          <%= image_tag "https://s3-us-west-2.amazonaws.com/nomcre/assets/CTAbutton.png", class: 'img-fluid', style: 'max-height:100px; max-width:200px;margin-top:-6px;' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/khaki/nomcre/creative/_typed_js.html.erb
<!-- START: We Are... -->
<div class="nk-box bg-dark-1 text-white text-center">
    <div class="bg-image bg-image-parallax op-1" ></div>
    <div class="nk-gap-5"></div>
    <div class="container">
        <h2 class="nk-title h1 mb-0">
            Are You
            <span class="db hidden-sm-up"></span>
            <span class="nk-typed bg-white text-dark-1 pl-8 pr-8 pt-5 pb-5 m-5 dib" data-back-delay="2000">
                <span>Talented</span>
                <span>Passionate</span>
                <span>Bold</span>
                <span>Artistic</span>
                <span>Nomadic</span>
                <span>Creative</span>
                <span>Funny</span>
            </span>
            <span class="db hidden-sm-up"></span>
            Enough?
        </h2>
    </div>
    <div class="nk-gap-5"></div>
</div>
<!-- END: We Are... -->