config/routes.rb
    resources :collection_items
    get '/feature', to: 'collections#make_featured', as: 'make_featured'
    get '/remove_feature', to: 'collections#remove_featured', as: 'remove_featured'
  end
  resources :locations
  resources :collection_items do
    get '/move_up', to: 'collection_items#move_up', as: 'move_up'
    get '/move_down', to: 'collection_items#move_down', as: 'move_down'
    get '/make_header', to: 'collection_items#make_header', as: 'make_header'
  end
  get '/collection_item/download/:id', to: 'collection_items#download', as:'download'
  resources :waitlists
  get 'waitlist/thank-you', to: 'waitlists#thank_you', as: 'thank_you'

  get 'waitlist/joined_waitlist', to: 'waitlists#send_joined_waitlist_email'
  get 'waitlist/creative_accepted', to: 'waitlists#send_user_accepted_email'
  get 'pages/send_announcement', to: 'pages#send_announcement'


  resources :proposals do
    get '/edit_details', to: 'proposals#edit_details', as: 'edit_details'
    get '/payment', to: 'proposals#payment'
    get 'create_request/:user_id', to: 'proposals#create_request', as: 'create_request'
    get 'accept_request', to: 'proposals#accept_request'
    get 'approve_request', to: 'proposals#approve_request'
    get 'send_email', to: 'proposals#send_email'
    get 'send_assigned_email', to: 'proposals#send_creative_assigned_email'
    get 'copy', to: 'proposals#copy', as: 'copy'
    get 'accepted', to: 'proposals#accepted_requests', as: "accepted_requests"
    get 'invoice', to: 'proposals#invoice', as: 'invoice'
    get 'wizard', to: 'proposals#wizard', as: 'wizard'
    resources :assistants
    resources :shot_list_items
  end

  get 'proposal/completed', to: 'proposals#completed', as: 'proposals_completed'
  get 'requests', to: 'proposal_requests#requests', as:'proposal_requests'
  get 'requests/:id/decline', to: 'proposal_requests#decline', as:'decline_proposal_request'
  get 'requests/:id/approve', to: 'proposal_requests#assign', as: 'assign_proposal'
  get 'proposal_requests/:id/send_request_accepted_email', to: 'proposal_requests#send_request_accepted_email'
  get 'proposal_requests/:id/send_request_created_email', to: 'proposal_requests#send_request_created_email'


  post 'charges/deposit/:proposal_id', to: 'charges#proposal_deposit', as: 'proposal_deposit'
  post 'charges/balance/:proposal_id', to: 'charges#proposal_balance', as: 'proposal_balance'
  post 'charges/use-it-deposit', to:'charges#create', as: 'charge_deposit'


  resources :companies do
    get 'send_welcome_email', to:'companies#send_welcome_email'

  end
  resources :invoices do
    post 'pay_with_stripe', to: 'invoices#pay_with_stripe', as: 'pay_with_stripe'
    resources :payments
  end
  #get 'invoices', to:'companies#invoices', as: 'invoices'
  devise_for :users
  get 'user/:id', to: "users#show", as: 'user_show'
  get 'users/:user_id/collections', to: "collections#index", as: 'user_collection'
  get 'user_type', to: 'users#user_type', as: 'user_type'
  get 'set_user_type', to:'users#set_user_type', as:'set_user_type'
  resources :pages do
    get '/publish', to: 'pages#publish', as:'publish'
    resources :page_sections
  end
  resources :page_sections
  resources :chatrooms
  resources :messages

  #notifications
  get '/notifications', to: 'notifications#index', as: 'notifications'

  #tasks

  resources :tasks do
    get '/complete', to: 'tasks#complete', as: 'task_complete'
  end

  #dashboards
  get '/dashboard/company', to: 'dashboards#company_dashboard', as: 'company_dashboard'
  get 'dashboard/creative', to: 'dashboards#creative_dashboard', as: 'creative_dashboard'
  get 'dashboard/accounting', to: 'dashboards#accounting_dashboard', as: 'accounting_dashboard'
  get 'dashboard/admin', to: 'dashboards#admin_dashboard', as: 'admin_dashboard'
  get 'home', to:'khaki#nomcre_home', as:'nomcre_home'
  get 'process', to:'khaki#nomcre_process', as: 'nomcre_process'
  get 'creative', to:'khaki#creative_landing', as: 'creative_landing'

  get 'contact', to:'khaki#contact', as: 'nomcre_contact'
  get 'about', to:'khaki#about', as: 'nomcre_about'
  get 'featured', to:'khaki#featured_creatives', as: 'featured_creatives'
  get 'creative_tutorial', to:'khaki#proposal_tutorial_creative', as: 'proposal_tutorial_creative'
  get 'company_tutorial', to:'khaki#proposal_tutorial_company', as: 'proposal_tutorial_company'
  get 'khaki/index', to:'khaki#index'
  get 'tos', to: 'khaki#tos', as: 'tos'
  get 'thew', to: 'khaki#thew', as:'thew'
  get 'THEW', to: 'khaki#thew', as:'THEW'
  get 'explainer', to: 'khaki#explainer', as:'explainer'
  get 'pricing', to: 'khaki#pricing', as:'pricing'

  get 'admin/users', to: 'admin#users', as: 'admin_users'
  get 'admin/projects', to: 'admin#projects', as: 'admin_projects'
  get 'admin/projects/new', to: 'admin#new_project', as: 'admin_new_project'
  get 'admin/project/:project_id/edit', to: 'admin#edit_project', as: 'admin_edit_project'
  get 'admin/project/:project_id/edit_price', to: 'admin#edit_project_price', as: 'admin_edit_project_price'
  get 'admin/shoots', to: 'admin#shoots', as: 'admin_shoots'
  get 'admin/shoot/:shoot_id/edit', to: 'admin#edit_shoot', as: 'admin_edit_shoot'
  get 'admin/proposals', to: 'admin#proposals', as: 'admin_proposals'
  get 'admin/schedule_items', to: 'admin#schedule_items', as: 'admin_schedule_items'
  get 'admin/collections', to: 'admin#collections', as: 'admin_collections'
  get 'admin/chats', to: 'admin#chatrooms', as: 'admin_chatrooms'
  get 'admin/black_dashboard', to: 'admin#black_dashboard', as: 'admin_black_dashboard'
  get 'admin/proposal_price/:proposal_id', to: 'admin#proposal_price', as: 'admin_proposal_price'
  get 'admin/deposit_paid/:proposal_id', to: 'admin#proposal_mark_deposit_paid', as: 'admin_proposal_mark_deposit_paid'
  get 'admin/balance_paid/:proposal_id', to: 'admin#proposal_mark_balance_paid', as: 'admin_proposal_mark_balance_paid'
  get 'admin/leads', to: 'admin#leads', as: 'admin_leads'
  post 'admin/leads/import', to: 'leads#import', as: 'import_leads'
  get 'admin/task_groups', to: 'admin#task_groups', as: 'admin_task_groups'
  get 'admin/task_group/:id/edit', to: 'admin#edit_task_group', as: 'admin_edit_task_group'
  get '/sales_materials', to: 'khaki#sales_materials', as: 'sales_materials'
  get '/faq', to: 'khaki#faq', as: 'faq'
  get '/landing_marketing', to: 'landing_pages#marketing', as: 'landing_marketing'
  get '/name-your-deposit', to: 'landing_pages#use_it_or_lose_it', as: 'use_it_or_lose_it'
  get '/thank_you', to: 'landing_pages#thank_you', as: 'landing_thank_you'
  get '/for/sales', to: 'pages#sales', as:'for_sales'
  get '/for/marketing', to: 'pages#marketing', as:'for_marketing'
  get '/for/non_profits', to: 'pages#non_profits', as:'for_non_profits'
  get '/for/start_ups', to: 'pages#start_ups', as:'for_start_ups'
  get '/for/consultants', to: 'pages#consultants', as:'for_consultants'
  get '/for/franchises', to: 'pages#franchises', as:'for_franchises'
  get '/sitemap', to: 'pages#sitemap'
  get '/noodles-email', to:'khaki#noodles_email', as: 'noodles_email'


  get '/emails/test/property_management', to: 'email_test#property_management', as: 'property_management_email'
  get '/emails/test/modeling_agency', to: 'email_test#modeling_agency', as: 'modeling_agency_email'
  get '/emails/test/newsletter', to: 'email_test#newsletter', as: 'newsletter_email'



  get 'black_dashboard/dashboard', to: 'black_dashboard#dashboard', as: 'black_dashboard_dashboard'
  get 'black_dashboard/pricing', to: 'black_dashboard#pricing', as: 'black_dashboard_pricing'
  get 'black_dashboard/timeline', to: 'black_dashboard#timeline', as: 'black_dashboard_timeline'
  get 'black_dashboard/login', to: 'black_dashboard#login', as: 'black_dashboard_login'
  get 'black_dashboard/profile', to: 'black_dashboard#profile', as: 'black_dashboard_profile'
  get 'black_dashboard/buttons', to: 'black_dashboard#buttons', as: 'black_dashboard_buttons'
  get 'black_dashboard/grid', to: 'black_dashboard#grid', as: 'black_dashboard_grid'
  get 'black_dashboard/panels', to: 'black_dashboard#panels', as: 'black_dashboard_panels'
  get 'black_dashboard/alerts', to: 'black_dashboard#alerts', as: 'black_dashboard_alerts'
  get 'black_dashboard/notifications', to: 'black_dashboard#notifications', as: 'black_dashboard_notifications'
  get 'black_dashboard/typography', to: 'black_dashboard#typography', as: 'black_dashboard_typography'
  get 'black_dashboard/forms_extended', to: 'black_dashboard#forms_extended', as: 'black_dashboard_forms_extended'
  get 'black_dashboard/forms_regular', to: 'black_dashboard#forms_regular', as: 'black_dashboard_forms_regular'
  get 'black_dashboard/forms_validation', to: 'black_dashboard#forms_validation', as: 'black_dashboard_forms_validation'
  get 'black_dashboard/forms_wizard', to: 'black_dashboard#forms_wizard', as: 'black_dashboard_forms_wizard'
  get 'black_dashboard/tables_regular', to: 'black_dashboard#tables_regular', as: 'black_dashboard_tables_regular'
  get 'black_dashboard/tables_extended', to: 'black_dashboard#tables_extended', as: 'black_dashboard_tables_extended'
  get 'black_dashboard/tables_datatables', to: 'black_dashboard#tables_datatables', as: 'black_dashboard_tables_datatables'
  get 'black_dashboard/maps_google', to: 'black_dashboard#maps_google', as: 'black_dashboard_maps_google'
  get 'black_dashboard/maps_full_screen', to: 'black_dashboard#maps_full_screen', as: 'black_dashboard_maps_full_screen'
  get 'black_dashboard/maps_vector', to: 'black_dashboard#maps_vector', as: 'black_dashboard_maps_vector'
  get 'black_dashboard/widgets', to: 'black_dashboard#widgets', as: 'black_dashboard_widgets'
  get 'black_dashboard/charts', to: 'black_dashboard#charts', as: 'black_dashboard_charts'
  get 'black_dashboard/calendar', to: 'black_dashboard#calendar', as: 'black_dashboard_calendar'
  get 'black_dashboard/nomcre_login', to: 'black_dashboard#nomcre_login', as: 'black_dashboard_nomcre_login'

  #root 'khaki#nomcre_home'

app/models/company.rb
class Company < ApplicationRecord
  #callbacks
  before_destroy :deconstruct

  #validations
  validates :name,    presence: true, case_sensitive: false
  validates :phone,   presence: true, case_sensitive: false
  validates :website, presence: true, case_sensitive: false

  #has_many
  has_many :users
  has_many :tasks
  has_many :proposals
  has_many :documents
  has_many :projects
  has_many :shoots
  has_many :invoices
  has_many :creative_requests
  has_many :chatrooms, through: :users
  has_many :payments
  has_many :stories

  #mount
  mount_uploader :logo, LogoUploader

  #collections
  def pending_requests
    CreativeRequest.where(company: self).where(accepted: false).where(declined: false)
  end

  def accepted_requests
    CreativeRequest.where(company: self).where(accepted: true)
  end

  def payments
    Payment.where(user: self.users)
  end

  #public methods
  def self.create_default_for_tests
    @user = nil
    @user = User.create!(name: 'Testy McTester',
                        email: 'testy@mctester.com',
                        password: 'password',
                        password_confirmation: 'password') if @user.nil?

    @company = Company.create!(name: 'Test',
                               logo: 'www.google.com',
                               phone: '1800-888-9999',
                               website: 'www.google.com',
                               instagram: '@instagram')
    @company.users << @user
    @company.save!
    @company
  end

  #deconstructor
  def deconstruct
    deconstruct_invoices
    deconstruct_users
  end

  def deconstruct_invoices
    self.invoices.each do |i|
      if !i.payment.nil?
        #TODO: Figure out what to do .. .maybe set up a dummy company? Maybe create a new dummy company?
        i.company = 1;
        i.save
      else
        i.destroy!
      end
    end
  end

  def deconstruct_users
    self.users.each do |u|
      u.company = nil?
      u.save!
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authorize, except: [:new, :create, :show, :send_welcome_email, :invoices]
  layout 'black_dashboard'

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.order(:created_at).page params[:page]
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    if company_params[:instagram] && company_params[:instagram].include?('@')
      @company.instagram = company_params[:instagram].gsub!('@', '')
    end

    respond_to do |format|
      #TODO: Move Company Assignment and User Profile Test to their own methods
      if @company.save
        if current_user.user_type == 'company'
          current_user.company = @company
          current_user.save
           if current_user.user_profile.nil?
            current_user.create_user_profile!(display_name: current_user.name)
          end
        end
        CompanyMailer.welcome_email(current_user).deliver_now
        format.html { redirect_to new_project_path, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      #TODO: Create helper for InstaFormat
       if company_params['instagram'].include?('@')

        new_insta = @company.instagram.gsub!('@', '')
        company_params[:instagram] = new_insta
      end
      if @company.update(company_params)
        format.html { redirect_to company_dashboard_path, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def invoices
    @company = current_user.company
  end

  def send_welcome_email
    set_company
    CompanyMailer.welcome_email(@company.users.first).deliver_now
    redirect_to @company
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      if params[:company_id]
         @company = Company.find(params[:company_id])
      else
        @company = Company.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :logo, :phone, :website, :instagram)
    end

    def authorize
      if current_user.role == 0
        return
      end
      unless  current_user && current_user.company == @company
        redirect_to root_path
      end
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/dashboards/partials/company/_company_dashboard_numeric_widgets.html.erb
<div class="row">
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3><%= ProposalRequest.where(requested_by: current_user).where(accepted: nil).count %></h3>

              <p>Open Requests</p>
            </div>
            <div class="icon">
              <i class="fa fa-question-circle"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h3><%= Proposal.where(company: current_user.company).where(completed: nil).count %></h3>

              <p>Open Proposals</p>
            </div>
            <div class="icon">
              <i class="fa fa-spinner"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3><%= Task.where(company_id: current_user.company.id).where(completed: false).count %></h3>

              <p>Open Tasks</p>
            </div>
            <div class="icon">
              <i class="fa fa-tasks"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3><%= Task.where(company_id: current_user.company.id).where(completed: false).where('deadline < ?', Date.today).count %></h3>
              <p>Overdue Tasks</p>
            </div>
            <div class="icon">
              <i class="fa fa-tasks"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
      </div>

app/views/dashboards/partials/company/_company_dashboard_task_list.html.erb
<div class="box box-warning">
  <div class="box-header ui-sortable-handle" style="cursor: move;">
    <i class="fa fa-clipboard"></i>

    <h3 class="box-title">To Do List</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <!-- See dist/js/pages/dashboard.js to activate the todoList plugin -->
    <% if Task.where(company: current_user.company).where(completed: false).count == 0 %>
      You Have No Open Tasks
    <% else %>
    <ul class="todo-list ui-sortable">
      <% Task.where(company: current_user.company).where(completed: false).order(:deadline).take(15).each do |task| %>
        <li>
          <!-- drag handle -->
          <span class="handle ui-sortable-handle">
            <i class="fa fa-ellipsis-v"></i>
            <i class="fa fa-ellipsis-v"></i>
          </span>
          <!-- checkbox -->
          <input type="checkbox" value="">
          <!-- todo text -->
          <span class="text"><%= task.description %></span>
          <!-- Emphasis label -->
          <% if task.deadline < Date.today + 10.days%>
            <small class="label label-danger">
          <% elsif  task.deadline < Date.today + 20.days %>
            <small class="label label-warning">
          <% else %>
            <small class="label label-success">
          <% end %>
            <i class="fa fa-clock-o"></i> <%= (task.deadline - Date.today).to_int %> days
          </small>
          <!-- General tools such as edit or delete-->
          <div class="tools">

            <%= link_to task_task_complete_path(task,  :redirect => "dashboard") do %><i class="fa fa-thumbs-up"></i> <% end %>
          </div>
        </li>
      <% end %>
    </ul>
    <div class="box-footer text-center">
      <%= link_to "View All", tasks_path, class: 'uppercase'%>
    </div>
    <% end %>
  </div>
  <!-- /.box-body -->
</div>

app/views/dashboards/partials/company/_company_open_proposals_widget.html.erb
<div class="box box-aqua">
  <div class="box-header with-border">
    <h3 class="box-title">Open Proposals</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <ul class="products-list product-list-in-box">
      <% Proposal.where(company: current_user.company).where(completed: nil).each do |p|%>
      <li class="item">
        <div class="product-img">
         <%= image_tag p.company.logo %>
       </div>
       <div class="product-info">
        <%= link_to p, class: 'product-title' do %>
        <%= p.title %>
        <span class="label label-success pull-right">
         <%= number_to_currency(p.price) %> USD
        </span>
        <% end %>
        <span class="product-description">
          <%= p.shoot_type %>
        </span>
        <span class="product-description">
          <%= p.content[0...100] unless p.content.nil? %>
        </span>
      </div>
    </li>
    <!-- /.item -->
    <% end %>
  </ul>
</div>
<!-- /.box-body -->
<div class="box-footer text-center">
  <%= link_to "View All", proposals_path, class: 'uppercase'%>
</div>
<!-- /.box-footer -->
</div>

app/views/dashboards/partials/company/_company_profile_check.html.erb
<%= render 'dashboards/partials/company/check/profile'%>

app/views/dashboards/partials/company/_company_proposal_check.html.erb
<% if current_user.company.proposals.nil? || current_user.company.proposals.count == 0 %>
  <% @proposal = Proposal.new %>
  <div class="box box-danger ">
    <div class='text-center'>
  <h2 class="box-title ">Set Up Your First Project</h2>
</div>
<div class="" style="color: black">
    <div class="box-header with-border text-center">
    </div>
    <div class="box-body">
      <%= form_for @proposal, class: 'form-horizontal' do |form| %>
      <div class='row'>
        <div class='col-md-3'></div>
        <div class='col-md-6'>
          <div class="box box-solid">
            <h3 class='text-center'> What Should I Be Called? </h3>
            <%= form.text_field :title, class: 'form-control', placeholder: "Give your project a cool name ... " %>
          </div>
        </div>
        <div class='col-md-3'></div>
      </div>
      <br> <br>

        <div class="row">
          <h3 class='text-center'>Is It A Photo Or Video Project? </h3><br>
          <div class="col-md-6">
            <div class='row'>
                <div class='col-md-4'></div>
                  <div class='text-center col-md-8  '>
                    <div class='rounded'>
                    <i class='fa fa-image fa-4x'></i>
                    <br><br>

                    <%= form.radio_button(:proposal_type, "photo", class:'icheck-me', :data => {:skin => 'square', :color => 'green'}) %>
                    <%= form.label(:proposal_type_photo, "Photo") %>
                  </div>
                </div>

              </div>


          </div>
          <div class="col-md-6">
             <div class='row'>

                <div class='text-center col-md-8'>

                    <i class='fa fa-video-camera fa-4x'></i>
                    <br><br>
                    <%= form.radio_button(:proposal_type, "video", class:'icheck-me', :data => {:skin => 'square', :color => 'green'}) %>
                    <%= form.label(:proposal_type_video, "Video") %>
                  </div>

                <div class='col-md-4'></div>

              </div>
          </div>
        </div>
      <br><br>
      <div class='row'>
        <div class='col-md-3'></div>
        <div class='col-md-3'>
          <div class="box box-solid">
            <div class="box-header with-border">
              <h4 class="box-title">When Do You Need This??</h4>
            </div>
            <div class='form-group text-center' style="margin:12px; padding-bottom: 12px;">
              <%= form.text_field :deadline,  class: 'form-control datepicker' %>
            </div>
          </div>
        </div>
        <div class='col-md-3'>
          <div class="box box-solid">
            <div class="box-header with-border">
              <h4 class="box-title">Location</h4>

            </div>
            <div class='form-group' style="margin:12px; padding-bottom: 12px;">
              <br>
              <%= form.select(:location_id, options_for_select(Location.locations_for_select), {}, {class: 'form-control'}) %>
            </div>
          </div>
        </div>
        <div class='col-md-3'></div>
      </div>
      <br><br>
      <div class='row'>

        </div>
      </div>

      <div class='row'>
        <div class='col-md-3'></div>
        <div class='col-md-6'>
          <%= form.hidden_field :company_id, :value => current_user.company.id %>
          <%= form.hidden_field :redirect, :value => 'wizard' %>
          <%= form.submit "Get Started", class: 'btn btn-success btn-block' %>
        </div>
        <div class='col-md-3'></div>
      </div>
      <br>

      <%end %>
    </div>

</div>






  </div>
<% else %>
  <div class="box box-success ">
    <h4><i class="icon fa fa-check"></i> Your First Proposal</h4>
    <hr>
    <div class='container'>
      <div class='row'>
        <div class='col-md-6'>
          <h4> Title: <%= current_user.company.proposals.first.title %> </h4>
        </div>
        <div class='col-md-6'>
           <h4><i class='fa fa-calendar'></i> Deadline: <%= current_user.company.proposals.first.deadline %> </h4>
        </div>
      </div>
      <br>
      <div class='row'>
        <div class='col-md-6'> <h4> Description: </h4> </div>
        <div class='col-md-6'> <h4><i class='fa fa-crosshairs'></i> Shot Type: </h4> </div>
      </div>
      <div class='row'>
        <div class='col-md-6'>
          <%= current_user.company.proposals.first.content %>
        </div>
         <div class='col-md-6'>
          <%= current_user.company.proposals.first.shoot_type %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboards/partials/company/_company_proposal_requests_widget.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Open Requests</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <ul class="products-list product-list-in-box">
      <% ProposalRequest.where(requested_by: current_user).where(accepted: nil).order(:created_at).each do |p|%>
      <li class="item">
        <div class="product-img">
         <%= image_tag p.proposal.company.logo %>
       </div>
       <div class="product-info">
        <%= link_to proposal_requests_path, class: 'product-title' do %>
        <%= User.find(p.requested_by).user_profile.display_name %>
        <span class="label label-success pull-right">
          <%= number_to_currency(p.proposal.price) %> USD
        </span>
        <% end %>
        <span class="product-description">
          <%= p.proposal.shoot_type %>
        </span>
        <span class="product-description">
          <%= p.proposal.content[0...100]%>
        </span>
      </div>
    </li>
    <!-- /.item -->
    <% end %>
  </ul>
</div>
<!-- /.box-body -->
<div class="box-footer text-center">
  <%= link_to "View All", proposals_path, class: 'uppercase'%>
</div>
<!-- /.box-footer -->
</div>

app/views/dashboards/partials/company/_company_user_profile_check.html.erb
<%= render 'dashboards/partials/company/check/user_profile' %>