config/routes.rb
Rails.application.routes.draw do

  
  post 'hbd/add_remote', to: 'happy_birthday_videos#create_from_remote', as: 'hbd_add_from_remote'
  post 'congrats/add_remote', to: 'congratulations_videos#create_from_remote', as: 'congrats_add_from_remote'
  resources :congratulations_videos
  resources :happy_birthday_videos
  get 'magic', to: 'headline_adlibs#magic', as: 'headline_adlibs_magic'
  resources :headline_adlibs do
    get 'personalization', to: 'headline_adlibs#personalization', as: 'headline_adlibs_personalization'

  end
  resources :feed_items
  get 'showcase', to:'khaki#creative_showcase', as: 'creative_showcase'
  get 'video_showcase', to:'khaki#video_showcase', as: 'video_showcase'
  get 'video-showcase', to:'khaki#video_showcase', as: 'video_showcase_hyphen'
  get 'videos', to:'khaki#video_showcase', as: 'video_showcase_naked'
  get 'model_showcase', to:'khaki#model_showcase', as: 'model_showcase'
  get 'playground', to: 'khaki#playground', as: 'playground'
  get 'continual_content', to: 'khaki#continual_content', as: 'continual_content'
  get 'stealth-mode', to: 'khaki#continual_content', as: 'stealth_continual_content'
  get 'continual-content', to: 'khaki#continual_content', as: 'h_continual_content'

  resources :shot_list_item_templates
  resources :task_groups do
    get 'add_to_shoot/:shoot_id', to: 'task_groups#copy_group_to_shoot', as:'copy_to_shoot'
    resources :shot_list_item_templates do
      get 'copy', to: 'shot_list_item_templates#copy', as: 'copy'
    end
  end
  get '/package/models', to:'package_types#models', as: 'package_types_models'
  get 'packages/:slug', to: 'package_types#show', as:'package_types_slug'
  get 'hbd/:slug', to: 'happy_birthday_videos#show', as:'hbd_by_slug'
  get 'hbd/by_name/:name', to: 'happy_birthday_videos#by_name', as:'hbd_by_name'
  get 'congrats/:slug', to: 'congratulations_videos#show', as:'congrats_by_slug'
  get 'congrats/by_name/:name', to: 'congratulations_videos#by_name', as:'congrats_by_name'
  resources :creative_requests
  resources :discount_codes
  resources :shoots do
    resources :shot_list_items
    resources :creative_requests
    resources :disclosures
    get '/tasks_popped', to: 'tasks#popped_out', as: 'tasks_poppedout'
    get 'task_groups/edit_names', to: 'task_groups#edit_names', as: 'edit_names'
    post 'task_groups/update_names', to: 'task_groups#update_names', as: 'update_names'
    resources :tasks
    get '/new_request/:user_id', to: 'shoots#create_creative_request', as: 'create_creative_request'
    get 'request_all', to:'shoots#request_all_available_creatives', as: 'request_all'
    get 'assign_creative/:creative_id', to: 'shoots#assign_creative', as: 'assign_creative'
    get 'assign_from_request/:creative_request_id', to: 'shoots#assign_from_request', as: 'assign_from_request'
  end
  resources :creative_requests do
    get 'accept', to:'creative_requests#accept', as: 'accept'
    get 'decline', to:'creative_requests#decline', as: 'decline'
  end
  resources :payments
  resources :projects do
    get 'payment', to: 'projects#payment', as: 'payment'
    get 'wizard', to: 'projects#wizard', as: 'wizard'
    patch 'update_price', to:'projects#update_price', as: 'update_price'
    resources :invoices
    resources :shoots
  end

  resources :documents
  get 'hello_world', to: 'hello_world#index'
  resources :package_types do
    get 'new-from-template', to:'package_types#new_from_template', as:'new_project_from_template'
  end
  get '/pages/Entrepreneur-Magazine', to: 'landing_pages#marketing', as: 'entrepreneur_marketing'
  get '/pages/linkedin-questionnaire', to: 'landing_pages#linkedin', as: 'linkedin'
  get '/headshots', to: 'landing_pages#headshots', as: 'headshots'
  resources :header_images
  resources :lead_notes

  resources :leads do
    resources :lead_notes
  end
  resources :showcase_videos do
    get '/play', to: 'showcase_videos#play', as: 'play'
    get '/play-vertical', to: 'showcase_videos#play_vertical', as: 'play_vertical'
  end
  resources :showcase_images
  resources :user_activities
  resources :shot_list_items
  mount ActionCable.server => '/cable'
  resources :assistants
  resources :user_profiles do
    get 'wizard', to: 'user_profiles#wizard', as:'wizard'
  end
  resources :contacts
  resources :schedule_items
  resources :collections do
    resources :collection_items
    get '/feature', to: 'collections#make_featured', as: 'make_featured'
    get '/remove_feature', to: 'collections#remove_featured', as: 'remove_featured'
  end
  resources :locations
  resources :collection_items do
    get '/move_up', to: 'collection_items#move_up', as: 'move_up'
    get '/move_down', to: 'collection_items#move_down', as: 'move_down'
    get '/make_header', to: 'collection_items#make_header', as: 'make_header'
  end
  get '/collection_item/download/:id', to: 'collection_items#download', as:'download'
  resources :waitlists
  get 'waitlist/thank-you', to: 'waitlists#thank_you', as: 'thank_you'

  get 'waitlist/joined_waitlist', to: 'waitlists#send_joined_waitlist_email'
  get 'waitlist/creative_accepted', to: 'waitlists#send_user_accepted_email'
  get 'pages/send_announcement', to: 'pages#send_announcement'


  resources :proposals do
    get '/edit_details', to: 'proposals#edit_details', as: 'edit_details'
    get '/payment', to: 'proposals#payment'
    get 'create_request/:user_id', to: 'proposals#create_request', as: 'create_request'
    get 'accept_request', to: 'proposals#accept_request'
    get 'approve_request', to: 'proposals#approve_request'
    get 'send_email', to: 'proposals#send_email'
    get 'send_assigned_email', to: 'proposals#send_creative_assigned_email'
    get 'copy', to: 'proposals#copy', as: 'copy'
    get 'accepted', to: 'proposals#accepted_requests', as: "accepted_requests"
    get 'invoice', to: 'proposals#invoice', as: 'invoice'
    get 'wizard', to: 'proposals#wizard', as: 'wizard'
    resources :assistants
    resources :shot_list_items
  end

  get 'proposal/completed', to: 'proposals#completed', as: 'proposals_completed'
  get 'requests', to: 'proposal_requests#requests', as:'proposal_requests'
  get 'requests/:id/decline', to: 'proposal_requests#decline', as:'decline_proposal_request'
  get 'requests/:id/approve', to: 'proposal_requests#assign', as: 'assign_proposal'
  get 'proposal_requests/:id/send_request_accepted_email', to: 'proposal_requests#send_request_accepted_email'
  get 'proposal_requests/:id/send_request_created_email', to: 'proposal_requests#send_request_created_email'


  post 'charges/deposit/:proposal_id', to: 'charges#proposal_deposit', as: 'proposal_deposit'
  post 'charges/balance/:proposal_id', to: 'charges#proposal_balance', as: 'proposal_balance'
  post 'charges/use-it-deposit', to:'charges#create', as: 'charge_deposit'


  resources :companies do
    get 'send_welcome_email', to:'companies#send_welcome_email'

  end
  resources :invoices do
    post 'pay_with_stripe', to: 'invoices#pay_with_stripe', as: 'pay_with_stripe'
    resources :payments
  end
  #get 'invoices', to:'companies#invoices', as: 'invoices'
  devise_for :users
  get 'user/:id', to: "users#show", as: 'user_show'
  get 'users/:user_id/collections', to: "collections#index", as: 'user_collection'
  get 'user_type', to: 'users#user_type', as: 'user_type'
  get 'set_user_type', to:'users#set_user_type', as:'set_user_type'
  resources :pages do
    get '/publish', to: 'pages#publish', as:'publish'
    resources :page_sections
  end
  resources :page_sections
  resources :chatrooms
  resources :messages

  #notifications
  get '/notifications', to: 'notifications#index', as: 'notifications'

  #tasks

  resources :tasks do
    get '/complete', to: 'tasks#complete', as: 'task_complete'
  end

  #dashboards
  get '/dashboard/company', to: 'dashboards#company_dashboard', as: 'company_dashboard'
  get 'dashboard/creative', to: 'dashboards#creative_dashboard', as: 'creative_dashboard'
  get 'dashboard/accounting', to: 'dashboards#accounting_dashboard', as: 'accounting_dashboard'
  get 'dashboard/admin', to: 'dashboards#admin_dashboard', as: 'admin_dashboard'
  get 'home', to:'khaki#nomcre_home', as:'nomcre_home'
  get 'process', to:'khaki#nomcre_process', as: 'nomcre_process'
  get 'creative', to:'khaki#creative_landing', as: 'creative_landing'

  get 'contact', to:'khaki#contact', as: 'nomcre_contact'
  get 'about', to:'khaki#about', as: 'nomcre_about'
  get 'featured', to:'khaki#featured_creatives', as: 'featured_creatives'
  get 'creative_tutorial', to:'khaki#proposal_tutorial_creative', as: 'proposal_tutorial_creative'
  get 'company_tutorial', to:'khaki#proposal_tutorial_company', as: 'proposal_tutorial_company'
  get 'khaki/index', to:'khaki#index'
  get 'tos', to: 'khaki#tos', as: 'tos'
  get 'thew', to: 'khaki#thew', as:'thew'
  get 'THEW', to: 'khaki#thew', as:'THEW'
  get 'explainer', to: 'khaki#explainer', as:'explainer'
  get 'pricing', to: 'khaki#pricing', as:'pricing'

  get 'admin/users', to: 'admin#users', as: 'admin_users'
  get 'admin/projects', to: 'admin#projects', as: 'admin_projects'
  get 'admin/projects/new', to: 'admin#new_project', as: 'admin_new_project'
  get 'admin/project/:project_id/edit', to: 'admin#edit_project', as: 'admin_edit_project'
  get 'admin/project/:project_id/edit_price', to: 'admin#edit_project_price', as: 'admin_edit_project_price'
  get 'admin/shoots', to: 'admin#shoots', as: 'admin_shoots'
  get 'admin/shoot/:shoot_id/edit', to: 'admin#edit_shoot', as: 'admin_edit_shoot'
  get 'admin/proposals', to: 'admin#proposals', as: 'admin_proposals'
  get 'admin/schedule_items', to: 'admin#schedule_items', as: 'admin_schedule_items'
  get 'admin/collections', to: 'admin#collections', as: 'admin_collections'
  get 'admin/chats', to: 'admin#chatrooms', as: 'admin_chatrooms'
  get 'admin/black_dashboard', to: 'admin#black_dashboard', as: 'admin_black_dashboard'
  get 'admin/proposal_price/:proposal_id', to: 'admin#proposal_price', as: 'admin_proposal_price'

app/controllers/black_dashboard_controller.rb
class BlackDashboardController < ApplicationController
  layout "black_dashboard_original"
end

app/helpers/black_dashboard_helper.rb
module BlackDashboardHelper
end

app/views/schedule_items/partials/black_dashboard/_index.html.erb
<%= link_to "<i class='fa fa-calendar'></i> Add Travel Plan".html_safe, new_schedule_item_path, class: 'btn btn-primary float-right' %>
<% if schedule_items.count == 0 %>
  <div class="alert alert-warning alert-dismissible text-center">
    <span><i class="fas fa-exclamation-circle"></i>
    You Havent Added Any Travel Plans Yet!</span>
  </div>
  <br>
  <br>
  <%= link_to "Lets Get Started <i class='fas fa-arrow-right'></i>".html_safe, new_schedule_item_path, class: 'btn btn-lg btn-success btn-block' %>
<% else %>
<div class="card card-timeline card-plain">
  <div class="card-body">
    <ul class="timeline">
      <% schedule_items.each do |si| %>
      <% color = cycle("info", "success", "primary", name:"color") -%>
      <li class="<%= cycle("", "timeline-inverted") -%>" >
        <div class="timeline-badge <%=color%>">
          <i class="tim-icons"><ion-icon name="<%= cycle("paper-plane", "jet", name:"plane") -%>"></ion-icon></i>
        </div>
        <div class="timeline-panel">
          <div class="timeline-heading">
            <span class="badge badge-pill badge-<%=color%>" >
              <ion-icon name='calendar'></ion-icon> <%= si.start_date.strftime("%A %b %d, %Y") %>
            </span>
          </div>
          <div class="timeline-body text-center">
            <ion-icon name='pin' size='large' class= 'text-primary'></ion-icon>
            <%= link_to schedule_item_path(si) do %>
            <h3 class="card-title" style="<%= cycle("color:white", "", name: "text-location") -%>"> <%= si.location.name %> </h3>
            <% if si.location.parent_id != nil %>
              <h5 class="card-title" style="<%= cycle("color:white", "", name: "text-parent") -%>"> <%= si.location.parent.name unless si.location.parent == nil %> </h5>
            <% end %>
            <% end %>

          </div>
          <h5 class='text-center'style="<%= cycle("color:white", "", name: "text-footer") -%>">
            <i class="ti-time"></i>
            <%= si.start_date.strftime("%A %b %d, %Y") %> - <%= si.end_date.strftime("%A %b %d, %Y") %>
          </h5>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/schedule_items/partials/black_dashboard/_schedule_item.html.erb
<li class="timeline-inverted">
  <div class="timeline-badge primary">
    <ion-icon name='airplane' > </ion-icon>
  </div>
  <div class="timeline-panel">
    <div class="timeline-heading">
      <span class="badge badge-primary"><%= schedule_item.location.name unless schedule_item.location.nil? %></span>
    </div>
    <div class="timeline-body">
      <p> <%= schedule_item.notes %></p>
      <br>
      <% if current_user == schedule_item.user %>
          <%= link_to 'Edit', edit_schedule_item_path(schedule_item), class: 'btn btn-primary' %>
          <%= link_to 'Destroy', schedule_item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger pull-right' %>
        <% end %>
    </div>
    <h5>
      <i class="fa fa-time"></i> <%= schedule_item.start_date.strftime("%a %b %d, %Y") unless schedule_item.start_date.nil?%> <span>Until</span>  <%= schedule_item.end_date.strftime("%a %b %d, %Y") unless schedule_item.end_date.nil?%>
    </h5>
  </div>
</li>

app/views/schedule_items/partials/black_dashboard/_show.html.erb
<div class="card card-timeline card-plain">
  <div class="card-body">
    <ul class="timeline timeline-simple">
      <%= render :partial => 'schedule_items/partials/black_dashboard/schedule_item', :locals => {:schedule_item => @schedule_item} %>
    </ul>
  </div>
</div>